// Le wiki — LES GARDES ET LES CHEVALIERS (onzième vague) : qui veille, où, quand ; la sommation (se rendre, ou pas) ;
// ce qui se cache. Rédigé d'après src/11-zzzzC-gardes.js et src/11-zzzzC1-gardes-jeu.js (et les notes de leur auteur).
// tools/wiki-build.js en fait la fiche « Les gardes : se rendre, ou pas » et ajoute aux fiches des deux cabanes (li:…)
// ce qu'il y a dedans ; « secret » se lit sous « révéler les secrets ». Les fiches des gardes eux-mêmes se font seules
// (ce sont des habitants : NPC_DATA).
'use strict';

const SECTIONS = [
  ['Deux protecteurs par lieu, pas un de plus', 'À Valbrume : Norbert Grosjean, le garde des ponts (comme avant), le jour ; le chevalier du guet, la nuit. À Clairpré : le garde champêtre, le jour ; le gendarme à cheval, la nuit. Ce sont les deux seuls vrais villages de la vallée (des rues, un marché, une foire) ; les Sources, les Planches et l’estive ont trois foyers chacun et leurs coutumes (on n’y veut pas d’uniforme) : le gendarme y passe en tournée, il n’y loge pas. Les nains et le Dessous ont leurs propres lois.\n\nChaque garde sait ce que son village sait : un crime connu à Valbrume ne l’est pas au hameau tant que la nouvelle n’y est pas arrivée. Ils meurent pour de bon, comme les autres habitants : un garde tué n’est pas remplacé.'],
  ['Le chevalier du guet', 'Ancien cuirassier, vingt-deux ans de service. Le titre est celui du vieux chef de la garde de nuit des villes : la commune l’a gardé, avec l’homme qui va avec. Casque à crinière, cuirasse, habit bleu, culotte blanche, bottes, sabre au fourreau (tiré quand il se bat), lanterne de ronde la nuit. Droit, taciturne ; il écrit tout dans le registre. Le plus solide des quatre : il ne rompt pas.'],
  ['Le garde champêtre', '« Halte-là ! … Ah, non, rien, l’habitude. » Assermenté : les chemins, les haies, les bornes, les chèvres. Képi bleu à bandeau garance, plaque de laiton et baudrier, fusil en bandoulière, le tambour des avis à la cabane. Bavard, pointilleux, il dresse procès-verbal de tout. Il tire avant de courir ; blessé, il rompt.'],
  ['Le gendarme à cheval', 'Détaché de la préfecture « pour six mois », il y a deux ans. Bicorne à cocarde, habit bleu nuit, buffleteries blanches, épaulettes, sabre. Il fait la nuit au hameau et, l’après-midi, la tournée des villages qui n’ont pas de garde ; il porte les nouvelles d’un village à l’autre, comme les colporteurs (« Quelles nouvelles ? »). Mistral, son cheval, reste à l’écurie de la cabane : on peut le flatter, pas le monter.'],
  ['Leur semaine', 'Valbrume : Grosjean le jour ; le chevalier passe le pont à 19 h, prend son poste au brasero et, de 21 h au matin, alterne d’heure en heure le poste et la ronde (le long des douves, côté dehors, et sur la route du nord). À 5 h, la relève au bout du pont (« Ohé, Norbert ! Rien cette nuit. » — « Rien ? Vraiment rien ? »). Il dort de 7 h à 14 h, puis passe l’après-midi en ville.\n\nClairpré : le garde champêtre le jour (le hameau, les rondes, le ranch ; le Foiredi, il ne quitte pas la foire) ; le gendarme la nuit, après la relève à la cabane vers 21 h ; il dort jusqu’à midi, panse Mistral, puis fait la tournée selon le jour (les Sources, les Planches, le ponton, la bibliothèque, le relais de chasse, la vieille ferme, le calvaire, le hameau) et rentre à l’écurie à 17 h 30. À deux, l’un dort quand l’autre veille ; la nuit, celui qui veille porte une lanterne.'],
  ['Quand il y a un problème', 'Dans leur village et un peu autour, ils accourent : l’homme au long manteau (le veilleur l’affronte ; le plus souvent il le blesse et l’homme s’enfuit, parfois il y reste ; Grosjean, lui, n’approche pas) ; l’homme au masque (il est touché et s’en va, ou il tue le garde ; c’est à vous de le démasquer) ; une bête dangereuse près des maisons (ours, sanglier, loups : le garde champêtre tire — manquée, la bête s’enfuit et il la chasse loin des maisons ; touchée, elle charge —, les autres vont au sabre ou à la pique) ; le feu (les seaux) ; un cri, un habitant qu’on frappe, un coup de feu (quelqu’un vient voir ; trop tard, c’est écrit au registre) ; un crime. Ceux qui dorment ne se lèvent que pour ce qui fait du bruit, tout près.'],
  ['La sommation : se rendre, ou pas', 'Un garde éveillé qui vous voit, et dont le village connaît un de vos crimes, vient à vous et vous somme : un choix s’ouvre.\n\n« Me rendre » : l’arrestation, puis le cachot (sous la maison de Grosjean), la rançon ou les jours de paille, comme avant. « Payer la prime sur-le-champ » : seulement pour un petit délit (vol, braconnage, effraction, intrusion, rébellion ; la prime en tout ne dépasse pas 450 pièces) et si l’on a la somme. « Refuser » : c’est la rébellion. Refermer le choix sans répondre : « Je ne le répéterai pas. » Rester planté là, c’est se laisser emmener ; s’éloigner, c’est refuser.'],
  ['La rébellion', 'Un délit de plus (une prime de base de 100 pièces, une fois par affaire ; un jour de cachot), et les coups, quel que soit le délit ; l’autre garde du lieu accourt. Fuir : ils lâchent quand on les a semés, et la prime monte de 50. Se battre : un garde blessé, c’est une agression ; tué, un meurtre. Se rendre plus tard : quand on est mal en point, le garde redemande (« Assez. Rendez-vous. »). Mis au tapis par un garde, on est arrêté, pas tué — sauf quand on est recherché pour un meurtre.'],
  ['Se rendre de soi-même', 'À un garde qui sait : la conversation commence par la prime (« Payer la prime », « Me rendre », « Refuser de le suivre »). À un garde qui ne sait rien (le crime n’est connu qu’ailleurs) : « Je viens me rendre » ; il apprend ce que la vallée sait, et il vous emmène. Les chasseurs de primes, les affiches, les témoins, l’oubli : rien ne change.'],
  ['Les chiffres', 'Un coup : Grosjean 18 à 26, le chevalier 24 à 32, le garde champêtre 12 à 18 (au fusil, 20 à 28, de 4 à 22 m, une chance sur deux, toutes les 3,2 s), le gendarme 22 à 30 ; un coup toutes les 1,4 à 1,9 s. Ils reprennent leurs forces au calme et sont remis à neuf chaque matin. Le choix refermé sans réponse : cinq secondes avant qu’il vous emmène ; il redemande de se rendre quand la vie passe sous 35, au plus toutes les 25 secondes. Après un refus, le cachot d’un premier vol coûte 565 pièces au lieu de 315.'],
];

const SECRET = 'Le sergent Ferrand devait seconder le chevalier ; il n’est jamais arrivé. Le chevalier lui garde son lit de camp — c’est le lit du passant : certaines nuits, quelqu’un y dort ; la couverture est tiède au matin, du côté du mur. Au coffre du guet : le brouillon d’un rapport jamais envoyé (on a frappé trois coups à l’heure où Ferrand devait arriver ; « Ferrand », a dit la voix, mais pas le mot du guet), l’ordonnance sur le guet et son article quatre (« Si le guet vient à manquer, le dernier qui l’a vu vivant prend la garde. »), une lettre jaunie de sa mère. Le registre a une page que le chevalier n’a pas écrite, de son écriture.\n\nLe garde champêtre : le procès-verbal de la mare (un homme qui marchait sur l’eau, « classé ») ; le garde d’avant, qui portait son nom, disparu au hameau abandonné (on a retrouvé son tambour sur une borne, les baguettes en croix, et c’est ce tambour-là qui sonne parfois tout seul) ; dans son carnet, une page à son nom qui n’est pas de sa main.\n\nLe gendarme : son rapport revenu une seule fois de la préfecture, avec dessous « Reçu. Restez. » ; la main posée à plat au fond du gué du moulin, que Mistral refuse de passer la nuit ; le cavalier sans lanterne dont le cheval ne faisait aucun bruit ; son ordre de mission, signé de sa propre main. La nuit rouge, le guet n’a rien vu et rien écrit.';

const CABANES = [
  { pages: ['li:g1_corps_garde'], titre: 'Dedans',
    texte: 'De l’autre côté des douves, au bout du pont nord : quand les ponts sont levés, c’est là que reste « celui qui reste avec ceux qui restent dehors ». Deux lits de camp — celui du chevalier, et celui du passant, qu’on peut prendre la nuit sans que personne ne s’en plaigne ; la table, le registre du guet (on le lit) et la lampe ; la cheminée ; la cuirasse de rechange sur son mannequin ; le râtelier ; les seaux ; le coffre du guet (le fouiller, c’est voler le guet). Dehors : le brasero (allumé tant que le veilleur de nuit est en vie), le banc, le tableau des avis, une lanterne ; au bout du pont, une guérite.',
    secret: 'Le lit du passant était celui du sergent Ferrand, qui n’est jamais arrivé : certaines nuits, quelqu’un y dort. Le registre et le coffre du guet en disent plus.' },
  { pages: ['li:g1_cabane_hameau'], titre: 'Dedans',
    texte: 'À l’entrée du hameau, sur la route qui vient de la ville. Deux lits de camp (le garde champêtre, le gendarme), la table, le registre des procès-verbaux, la lampe, le poêle, le râtelier, le tambour, les seaux, le coffre des gardes. Dehors : le brasero du gendarme, le banc, le tableau des avis, la lanterne ; contre le mur de gauche, l’écurie en appentis et Mistral. La nuit, quand le garde champêtre dort, la porte est fermée : on frappe (« Le gendarme est de garde, il est dehors, allez le voir ! »).',
    secret: 'Le tambour de la cabane a appartenu au garde d’avant, disparu au hameau abandonné : c’est lui qui sonne parfois tout seul.' },
];

module.exports = { SECTIONS, SECRET, CABANES };
